import { Button, Text, Link } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import React from "react"
import { useRecoilState } from "recoil"
import { countState } from "../constants/countState"
import styles from "../styles/Home.module.css"
import { useRouter } from "next/router"

const Home: NextPage = () => {
  const router = useRouter()
  const [count, setCount] = useRecoilState(countState)
  const increment = (c: number) => {
    return c + 1
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text>{count}</Text>
        <Button onClick={() => setCount(increment)}>increment</Button>
        <Button onClick={() => router.push("/about")}>router link</Button>
        <Link href="/about">about</Link>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
